#!/bin/bash
# Convert timexdr text *.gps files into XML *.gpx format.
# Written by Jan Merka, 2006.
#
# $Id$

TMP_FILE=/tmp/$( basename $0 )_$$.tmp
TIME_ZONE=$( date +%:z )
FIX_TYPE=( "none" "none" "2d" "3d" )
ROUTE_NAME="timexdr"
ROUTE_DESC="Recorded by Timex Data Recorder"
ROUTE_ID="1"
AUTHOR=

usage() {
  echo "Convert timexdr GPS data format to GPX, the GPS data exchange format."
  echo
  echo "Usage: $( basename $0 ) [OPTIONS] file1"
  echo "Options:"
  echo -e "  -a <author>\tThe person or organization who created the GPX file."
  echo -e "  -d <desc>\tA text description of the recorded route."
  echo -e "  -h\t\tDisplay usage information (this message)." 
  echo -e "  -i <number>\tGPS route number [$ROUTE_ID]."
  echo -e "  -n <name>\tGPS route name [$ROUTE_NAME]"
  echo -e "  -o <out_file>\tSpecify a name for the output file."
  echo -e "  -z <tzone>\tProvide time zone for the GPS data if different"
  echo -e "\t\tfrom localtime on the computer. Example, '-06:00' or '+05:00'." 
  echo
  echo "File 'file1' holds timexdr GPS (*.gps) data."
  echo "The GPX data are send to standard output."
  exit 1
}

get_file_type() {
  while [ $# -gt 0 ]; do
    [ -f "$1" ]  ||  ( echo "Input file $1 does not exist." ; exit 1 )
    if grep -q "HRM" "$1" 2>/dev/null ; then
	echo "HRM"
    elif grep -q "GPS" "$1" 2>/dev/null ; then
	echo "GPS"
    fi
    shift 1
  done
}

print_bounds() {
  unset minlon maxlon minlat maxlat 

  minlon=$( tail -n 1 $TMP_FILE  |  cut -f 1 )
  maxlon=$( tail -n 1 $TMP_FILE  |  cut -f 2 )
  minlat=$( tail -n 1 $TMP_FILE  |  cut -f 3 )
  maxlat=$( tail -n 1 $TMP_FILE  |  cut -f 4 )

  echo -e -n "<bounds minlat=\"$minlat\" minlon=\"$minlon\" "
  echo               "maxlat=\"$maxlat\" maxlon=\"$maxlon\"></bounds>"
}

gpx_header() {
  echo "<?xml version=\"1.1\"?>"
  echo "<gpx version=\"1.1\" creator=\"timexdr\">"
  echo "<desc>${ROUTE_DESC}</desc>"
  [ "x${AUTHOR}" == "x" ]  ||
  echo "<author>${AUTHOR}</author>"
  echo "<time>$( date -u +%FT%XZ )</time>"
  print_bounds
}

gpx_tail() {
  echo "</gpx>"
}

route_header() {
  echo "<rte>"
  echo "<name>${ROUTE_NAME}</name>"
  echo "<desc>${ROUTE_DESC}</desc>"
  echo "<src>Timex Data Recorder</src>"
  echo "<number>${ROUTE_ID}</number>"
}

route_tail() {
  echo "</rte>"
}

rte_point() {
#	datetime lon lat alt spd pace dst acq
  echo "<rtept lat=\"$lat\" lon=\"$lon\">"
  echo " <ele>$alt</ele>"
  echo " <time>${datetime}${TIME_ZONE:-Z}</time>"
  echo " <fix>${FIX_TYPE[$acq]}</fix>"
  echo "</rtept>"
}

[ $# -eq 0 ]  &&  usage

# Process options
while getopts ":a:d:hi:n:o:z:" OPT; do
  case $OPT in
   a)  AUTHOR="$OPTARG"	    	;;
   d)  ROUTE_DESC="$OPTARG" 	;;
   h)  usage             	;;
   i)  ROUTE_ID="$OPTARG" 	;;
   n)  ROUTE_NAME="$OPTARG" 	;;
   o)  out_file=$OPTARG 	;;
   z)  TIME_ZONE=$OPTARG     	;;
   *)  echo "Unimplemented option -${OPTARG}"
       usage            	;;
  esac
done
  
# Decrement the argument pointer so it points to next argument. $1 now 
# references the first non option item supplied on the command line if
# one exists.
shift $(( $OPTIND - 1 ))

# Check the data file
[ $( get_file_type "$1" ) == "GPS" ]  ||  usage
 
grep -v -e "GMT" -e "packet"  "$1"  |
gawk '{ 
  counter += 1; 
  if (counter == 1) { 
  	split($3, ymd, "-"); 
  	split($4, hms, ":"); 
  	#print $3, $4 
  }; 
  if (counter > 2) { 
	split($1, time, ":"); 
	dt_sec = time[3] + hms[3]; 
	dt_min = time[2] + hms[2]; 
	dt_hr  = time[1] + hms[1]; 
	dt_day = ymd[3] ; 
	dt_month = ymd[2]; 
	dt_yr = ymd[1] ; 
	lon = $11;
	lat = $10;
	alt = $7;
	dist = $6;
	spd = $5;
	if (spd > 0)    { pace = 60/spd } else { pace = 999 };
	if (pace > 999) { pace = 999 };
	split($3, acq, "x");
	
	# Make sure parameters are within limits
	while (dt_sec >= 60) { dt_sec -= 60; dt_min += 1 }; 
	while (dt_min >= 60) { dt_min -= 60; dt_hr += 1}; 
	while (dt_hr >= 24)  { dt_hr -= 24; dt_day += 1 }; 
	if (lon >= 180)      { lon -= 360 };
	
	# Find min and max longitude/latitude
	if (acq[2] > 0) {
		cntr2 += 1;
		if (cntr2 == 1) {
			minlat = lat;
			maxlat = lat;
			minlon = lon;
			maxlon = lon;
		} else {
			if (minlat > lat) {minlat = lat};
			if (maxlat < lat) {maxlat = lat};
			if (minlon > lon) {minlon = lon};
			if (maxlon < lon) {maxlon = lon};
			}
	}

	#print $1; 
	printf "%4.4d-%2.2d-%2.2dT%2.2d:%2.2d:%05.2f\t", 
		dt_yr, dt_month, dt_day, dt_hr, dt_min, dt_sec	;
	printf "%15.9f\t%14.9f\t%7.1f\t%5.1f\t%9.5f\t%7.3f\t%1.1d\n",
		lon, lat, alt, spd, pace, dist, acq[2] ; 
   };
 } END { 
   printf "%15.9f\t%15.9f\t%14.9f\t%14.9f\n",
   	minlon, maxlon, minlat, maxlat ;
 }' > $TMP_FILE 

gpx_header
route_header
sed -i "\$d"  $TMP_FILE
cat           $TMP_FILE  |
while read  datetime lon lat alt spd pace dst acq; do
  rte_point
done
route_tail
gpx_tail
rm  -f $TMP_FILE
