#!/bin/bash
# Convert timexdr text *.gps files into XML *.gpx format.
# Written by Jan Merka, 2006.
#
# $Id$

TMP_FILE=/tmp/$( basename $0 )_$$.tmp
FIX_TYPE=( "none" "none" "2d" "3d" )
ROUTE_NAME="timexdr"
ROUTE_DESC="Recorded by Timex Data Recorder"
ROUTE_ID="1"
AUTHOR=

usage() {
  echo "Convert timexdr GPS data format to GPX, the GPS data exchange format."
  echo
  echo "Usage: $( basename $0 ) [OPTIONS] file1"
  echo "Options:"
  echo -e "  -a <author>\tThe person or organization who created the GPX file."
  echo -e "  -d <desc>\tA text description of the recorded route."
  echo -e "  -h\t\tDisplay usage information (this message)." 
  echo -e "  -i <number>\tGPS route number [$ROUTE_ID]."
  echo -e "  -n <name>\tGPS route name [$ROUTE_NAME]"
  echo -e "  -o <out_file>\tSpecify a name for the output file."
  echo -e "\t\tfrom localtime on the computer. Example, '-06:00' or '+05:00'." 
  echo
  echo "File 'file1' holds timexdr GPS (*.gps) data."
  echo "The GPX data are send to standard output."
  exit 1
}

get_file_type() {
  while [ $# -gt 0 ]; do
    [ -f "$1" ]  ||  ( echo "Input file $1 does not exist." ; exit 1 )
    if grep -q "HRM" "$1" 2>/dev/null ; then
	echo "HRM"
    elif grep -q "GPS" "$1" 2>/dev/null ; then
	echo "GPS"
    fi
    shift 1
  done
}

print_bounds() {
  unset minlon maxlon minlat maxlat 

  minlon=$( tail -n 1 $TMP_FILE  |  cut -f 1 )
  maxlon=$( tail -n 1 $TMP_FILE  |  cut -f 2 )
  minlat=$( tail -n 1 $TMP_FILE  |  cut -f 3 )
  maxlat=$( tail -n 1 $TMP_FILE  |  cut -f 4 )

  echo -e -n "<bounds minlat=\"$minlat\" minlon=\"$minlon\" "
  echo               "maxlat=\"$maxlat\" maxlon=\"$maxlon\"></bounds>"
}

gpx_header() {
  echo "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>"
  echo "<gpx xmlns=\"http://www.topografix.com/GPX/1/1\" version=\"1.1\" creator=\"$( timexdr -V )\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd\">"
  echo "<metadata>"
  echo "<desc>${ROUTE_DESC}</desc>"
  [ "x${AUTHOR}" == "x" ]  ||
  echo "<author><name>${AUTHOR}</name></author>"
  echo "<time>$( date -u +%FT%XZ )</time>"
  print_bounds
  echo "</metadata>"
}

gpx_tail() {
  echo "</gpx>"
}

route_header() {
  echo "<trk>"
  echo "<name>${ROUTE_NAME}</name>"
  echo "<desc>${ROUTE_DESC}</desc>"
  echo "<src>Timex Data Recorder</src>"
  echo "<number>${ROUTE_ID}</number>"
  echo "  <trkseg>"
}

route_tail() {
  echo "  </trkseg>"
  echo "</trk>"
}

rte_point() {
#	datetime lon lat alt spd pace dst acq
  echo "<trkpt lat=\"$lat\" lon=\"$lon\">"
  echo " <ele>$alt</ele>"
  echo " <time>${datetime:0:25}:${datetime:25:2}</time>"
  echo " <fix>${FIX_TYPE[$acq]}</fix>"
  echo "</trkpt>"
}

[ $# -eq 0 ]  &&  usage

# Process options
while getopts ":a:d:hi:n:o:z:" OPT; do
  case $OPT in
   a)  AUTHOR="$OPTARG"	    	;;
   d)  ROUTE_DESC="$OPTARG" 	;;
   h)  usage             	;;
   i)  ROUTE_ID="$OPTARG" 	;;
   n)  ROUTE_NAME="$OPTARG" 	;;
   o)  out_file=$OPTARG 	;;
   *)  echo "Unimplemented option -${OPTARG}"
       usage            	;;
  esac
done
  
# Decrement the argument pointer so it points to next argument. $1 now 
# references the first non option item supplied on the command line if
# one exists.
shift $(( $OPTIND - 1 ))

# Check the data file
[ $( get_file_type "$1" ) == "GPS" ]  ||  usage
 
grep -v -e "GMT" -e "packet"  "$1"  |
gawk '{ 
  counter += 1; 
  if (counter == 1) { 
  	split($3, ymd, "-"); 
  	split($4, hms, ":"); 
  	#print $3, $4 
  }; 
  if (counter > 2) { 
	# Print time
	printf "%sT%s\t", $1, $2;

	lon = $12;
	lat = $11;
	alt = $8;
	dist = $7;
	spd = $6;
	acq = $4;
	if (spd > 0)    { pace = 60/spd } else { pace = 999 };
	if (pace > 999) { pace = 999 };
	
	# Make sure parameters are within limits
	if (lon >= 180)      { lon -= 360 };
	
	# Find min and max longitude/latitude
	if (acq > 0) {
		cntr2 += 1;
		if (cntr2 == 1) {
			minlat = lat;
			maxlat = lat;
			minlon = lon;
			maxlon = lon;
		} else {
			if (minlat > lat) {minlat = lat};
			if (maxlat < lat) {maxlat = lat};
			if (minlon > lon) {minlon = lon};
			if (maxlon < lon) {maxlon = lon};
			}
	}

	printf "%15.9f\t%14.9f\t%7.1f\t%5.1f\t%9.5f\t%7.3f\t%1.1d\n",
		lon, lat, alt, spd, pace, dist, acq ; 
   };
 } END { 
   printf "%15.9f\t%15.9f\t%14.9f\t%14.9f\n",
   	minlon, maxlon, minlat, maxlat ;
 }' > $TMP_FILE 

gpx_header
route_header
sed -i "\$d"  $TMP_FILE
cat           $TMP_FILE  |
while read  datetime lon lat alt spd pace dst acq; do
  rte_point
done
route_tail
gpx_tail
rm  -f $TMP_FILE
